=== youarebin/WebService/XMLExamples/Invoice/BookML.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % dateAttr " year CDATA #REQUIRED
					month (01|02|03|04|05|06|07|08|09|10|11|12) #REQUIRED
					day CDATA #REQUIRED">

<!ENTITY % bookAttr "id ID #REQUIRED
		       		categories IDREFS #REQUIRED">

<!ENTITY % commonBookInfo1 "title, author+, publisher, publishDate, price, discountRate">		
	
<!ENTITY % commonBookInfo2 "pages, rating, category+, coverImage?, description?, review">	

<!ELEMENT catalog (bookList,bookCategory)>
<!ELEMENT bookList (book*, eBook*, newEbook*)>

<!ELEMENT book (%commonBookInfo1;,revisionDate*,%commonBookInfo2;)>
<!ELEMENT eBook (%commonBookInfo1;, originalTitle, translator, revisionDate*, %commonBookInfo2;, format, size, period)>
<!ELEMENT newEbook (%commonBookInfo1;, originalTitle, translator, %commonBookInfo2;, format, size, period)>

<!ATTLIST book %bookAttr;>
<!ATTLIST eBook %bookAttr;>
<!ATTLIST newEbook %bookAttr;>

<!ELEMENT title (#PCDATA)>
<!ELEMENT originalTitle (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT translator (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>

<!ELEMENT publishDate (#PCDATA)>
<!ATTLIST publishDate %dateAttr;>
<!ELEMENT revisionDate (#PCDATA)>
<!ATTLIST revisionDate %dateAttr;>

<!ELEMENT price (listPrice, salesPrice)>
<!ATTLIST price currency (won|dollar|yen) "won"
				listPrice CDATA #REQUIRED
				salesPrice CDATA #REQUIRED>
<!ELEMENT listPrice (#PCDATA)>
<!ELEMENT salesPrice (#PCDATA)>
<!ATTLIST salesPrice discountRate CDATA #REQUIRED>	
			
<!ELEMENT discountRate (#PCDATA)>	
<!ELEMENT pages (#PCDATA)>	
<!ELEMENT rating (#PCDATA)>

<!ELEMENT bookCategory (category*)> 
<!ELEMENT category (category*)>
<!ATTLIST category cid ID #REQUIRED
				   name CDATA #REQUIRED>
				   
<!NOTATION jpeg PUBLIC "image/jpeg" "imageViewer.exe">
<!NOTATION gif PUBLIC "image/gif" "photoViewer.exe">
<!ELEMENT coverImage (#PCDATA)>
<!ATTLIST coverImage src CDATA #REQUIRED
					type NOTATION (gif|jpeg) "jpeg">	
					
<!ELEMENT description (#PCDATA)>
<!ELEMENT review (#PCDATA)>								   
<!ELEMENT format (#PCDATA)>
<!ATTLIST format value (EPUB|PDF|StremText|StreamImage) "EPUB">
<!ELEMENT size (#PCDATA)>
<!ATTLIST size unit CDATA #REQUIRED>
<!ELEMENT period (#PCDATA)>

=== youarebin/WebService/XMLExamples/Invoice/bookCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "BookML.dtd" >
<catalog>
  <bookList>
    <book categories="c101-1-1" id="isbn-895467277-9">
      <title>이토록 평범한 미래</title>
      <author>김연수</author>
      <publisher>문학동네</publisher>
      <publishDate day="15" month="11" year="2023">publishDate</publishDate>
      <price currency="won" listPrice="14000" salesPrice="12600">
        <listPrice>listPrice</listPrice>
        <salesPrice discountRate="">salesPrice</salesPrice>
      </price>
      <discountRate>discountRate</discountRate>
      <revisionDate day="" month="01" year="">revisionDate</revisionDate>
      <pages>276</pages>
      <rating>9.4</rating>
      <category cid="idvalue1" name="">
        <category cid="idvalue2" name=""/>
      </category>
      <coverImage src="https://image.yes24.com/goods/113737429/XL" type="jpeg">coverImage</coverImage>
      <description>김연수 9년 만의 신작 소설집. 종말 이후의 사랑에 대한 여덟 편의 이야기. 작가가
최근 2~3년간 집중적으로 단편 작업에 매진한 끝에 선보이는 소설집으로, ‘시간’을 인식하는 김연수의 변화된
시각을 확인할 수 있게 한다. 김연수는 과거에서 미래를 향해 흐르는 것으로만 여겨지는 시간을 다르게 정의
함으로써 우리가 현재의 시간을, 즉 삶을 새롭게 상상할 수 있는 가능성을 아름답고 서정적인 언어로 설득해
낸다. 특별한 점은 그 가능성이 ‘이야기’의 형태로 전달된다는 것이다. …</description>
      <review>>&quot;우리가 달까지 갈 수는 없지만 갈 수 있다는 듯이 걸어갈 수는 있다. 달이 어디
에 있는지 찾을 수만 있다면. 마찬가지로 우리는 달까지 걸어가는 것처럼 살아갈 수 있다. 희망의 방향만 찾을
수 있다면.&quot; (-&lt;진주의 결말&gt; 중에서) 어떤 희망의 방향을 찾는 일은 때로 쉽고 어렵다. 이런 소설
을 읽으면서 작은 격려와 응원을 받는 기분이다. 좋은 소설에 대해, 우리가 기다렸던 소설이 이런 게 아닐까
싶다</review>
    </book>
    <eBook categories="c102-1 c103-2" id="isbn-978-893497246-4">
      <title>사피엔스</title>
      <author>유발 하라리</author>
      <publisher>김영사</publisher>
      <publishDate day="" month="01" year="">publishDate</publishDate>
      <price currency="won" listPrice="" salesPrice="">
        <listPrice>listPrice</listPrice>
        <salesPrice discountRate="">salesPrice</salesPrice>
      </price>
      <discountRate>discountRate</discountRate>
      <originalTitle>>Sapiens: A Brief History of Humankind</originalTitle>
      <translator>translator</translator>
      <revisionDate day="" month="01" year="">revisionDate</revisionDate>
      <pages>pages</pages>
      <rating>rating</rating>
      <category cid="idvalue4" name="">
        <category cid="idvalue5" name=""/>
      </category>
      <coverImage src="" type="jpeg">coverImage</coverImage>
      <description>>변방의 유인원 호모 사피엔스는 어떻게 세상의 지배자가 되었는가? 수렵채집을 하
던 우리 조상들은 어떻게 한 곳에 모여 도시와 왕국을 건설하였는가? 인간은 왜 지구 역사상 가장 치명적인
동물이 되었는가? 과학은 모든 종교의 미래인가? 인간의 유효기간은 언제까지인가? 멀고먼 인류의 시원부터
인지혁명, 농업혁명, 과학혁명을 거쳐 끊임없이 진화해온 인간의 역사를 생물학, 경제학, 종교학, 심리학, 철학
등 여러 학문의 경계를 넘나들며 다양하고 생생하게 조명한 전인미답의 문제작. 호모 사피엔스부터 인공지능
까지, 기나긴 역사의 시간을 한 권으로 써내려간 문명 항해기.</description>
      <review>review</review>
      <format value="EPUB">format</format>
      <size unit="MB">size</size>
      <period>30</period>
    </eBook>
    <newEbook categories="c102-2" id="isbn-978-890128069-1">
      <title>title</title>
      <author>author</author>
      <publisher>publisher</publisher>
      <publishDate day="" month="01" year="">publishDate</publishDate>
      <price currency="won" listPrice="" salesPrice="">
        <listPrice>listPrice</listPrice>
        <salesPrice discountRate="">salesPrice</salesPrice>
      </price>
      <discountRate>discountRate</discountRate>
      <originalTitle>originalTitle</originalTitle>
      <translator>translator</translator>
      <pages>pages</pages>
      <rating>rating</rating>
      <category cid="idvalue7" name="">
        <category cid="idvalue8" name=""/>
      </category>
      <coverImage src="" type="jpeg">coverImage</coverImage>
      <description>description</description>
      <review>review</review>
      <format value="EPUB">format</format>
      <size unit="">size</size>
      <period>10</period>
    </newEbook>
  </bookList>
  <bookCategory>
    <category cid="c101" name="문학">
      <category cid="c101-1" name="소설"/>
      	<category cid="c101-1-1" name="한국소설"></category>
    </category>
    <category cid="c102" name="인문">
 		<category cid="c102-1" name="철학/사상"></category>
 		<category cid="c102-2" name="심리학"></category>
 	</category>
 	<category cid="c103" name="역사">
		 <category cid="c103-1" name="한국사"></category>
		 <category cid="c103-2" name="세계사"></category>
 </category>
  </bookCategory>
</catalog>
